lm_eval:
  enable: true
  model: vllm
  model_args:
    dtype: auto
    pretrained: zjiayu064/DeepSeek-V2-Lite-BitsMoE-2bit
    trust_remote_code: true
    tensor_parallel_size: 1
    gpu_memory_utilization: 0.90
  device: auto
  apply_chat_template: false
  batch_size: auto
  tasks:
    - gsm8k
  extra_args:
    confirm_run_unsafe_code: true

ppl:
  enable: false
  model_name_or_path: zjiayu064/DeepSeek-V2-Lite-BitsMoE-2bit
  use_fa2: true
  trust_remote_code: true
  seq_len: 2048
  max_samples: 512
  stride: 512


runtime:
  seed: 42
